#
# This file is part of Python Client Library for STAC.
# Copyright (C) 2019 INPE.
#
# Python Client Library for STAC is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

version: 2

sphinx:
    configuration: doc/sphinx/conf.py

formats: []

python:
    version: 3.7

    install:
        - method: pip
          path: .
          extra_requirements:
              - docs
    system_packages: true
